#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json
import uuid

import websockets


async def recv_json(ws: websockets.WebSocketClientProtocol, timeout: float = 5.0) -> dict:
    raw = await asyncio.wait_for(ws.recv(), timeout=timeout)
    return json.loads(raw)


async def run(args: argparse.Namespace) -> int:
    session_id = args.session_id or f'reconnect-{uuid.uuid4()}'
    live_url = f"{args.ws_base.rstrip('/')}/ws/live/{session_id}"

    print(f'Using session_id={session_id}')

    async with websockets.connect(live_url, max_size=2**20) as ws:
        first = await recv_json(ws)
        if first.get('type') != 'connection_state' or first.get('state') != 'connected':
            print(f'FAIL: unexpected first message {first}')
            return 1

        await ws.send(
            json.dumps(
                {
                    'type': 'user_command',
                    'session_id': session_id,
                    'timestamp': '2026-03-04T00:00:00Z',
                    'command': 'request_human_help',
                }
            )
        )
        second = await recv_json(ws)
        if second.get('type') != 'assistant_text':
            print(f'FAIL: expected assistant_text before reconnect, got {second}')
            return 2

    await asyncio.sleep(0.4)

    async with websockets.connect(live_url, max_size=2**20) as ws2:
        reconnect_msg = await recv_json(ws2)
        if reconnect_msg.get('type') != 'connection_state' or reconnect_msg.get('state') != 'connected':
            print(f'FAIL: reconnect did not report connected state: {reconnect_msg}')
            return 3

        await ws2.send(
            json.dumps(
                {
                    'type': 'user_command',
                    'session_id': session_id,
                    'timestamp': '2026-03-04T00:00:00Z',
                    'command': 'describe_detailed',
                }
            )
        )
        reply = await recv_json(ws2)
        if reply.get('type') != 'assistant_text':
            print(f'FAIL: expected assistant_text after reconnect, got {reply}')
            return 4

    print('PASS: reconnect flow succeeded.')
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Reconnect smoke test for /ws/live/{session_id}.')
    parser.add_argument('--ws-base', default='ws://127.0.0.1:8000', help='Backend websocket base URL')
    parser.add_argument('--session-id', default='', help='Session ID (autogenerated when empty)')
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    exit_code = asyncio.run(run(args))
    raise SystemExit(exit_code)


if __name__ == '__main__':
    main()
