#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys
import uuid
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
try:
    from fastapi.testclient import TestClient
except ModuleNotFoundError:
    site_packages = (
        ROOT
        / 'backend'
        / '.venv'
        / 'lib'
        / f'python{sys.version_info.major}.{sys.version_info.minor}'
        / 'site-packages'
    )
    if site_packages.exists():
        sys.path.insert(0, str(site_packages))
        from fastapi.testclient import TestClient
    else:
        raise

sys.path.insert(0, str(ROOT / 'backend'))

import main as backend_main  # type: ignore  # noqa: E402


def recv_until_type(ws: Any, target: str, max_messages: int = 20) -> dict[str, Any]:
    for _ in range(max_messages):
        payload = ws.receive_json()
        if payload.get('type') == target:
            return payload
    raise RuntimeError(f'Timed out waiting for message type={target}')


def run(args: argparse.Namespace) -> int:
    session_id = args.session_id or f'reconnect-asgi-{uuid.uuid4()}'
    print(f'Using session_id={session_id}')
    live_path = f'/ws/live/{session_id}'
    if args.ws_token:
        live_path = f'{live_path}?token={args.ws_token}'

    with TestClient(backend_main.app) as client:
        with client.websocket_connect(live_path) as ws:
            ws.send_json({'type': 'heartbeat', 'session_id': session_id, 'timestamp': '2026-03-05T00:00:00Z'})
            first = recv_until_type(ws, 'heartbeat_ack')
            if first.get('session_id') != session_id:
                print(f'FAIL: heartbeat ack mismatch: {first}')
                return 1

            ws.send_json(
                {
                    'type': 'user_command',
                    'session_id': session_id,
                    'timestamp': '2026-03-05T00:00:00Z',
                    'command': 'request_human_help',
                }
            )
            reply = recv_until_type(ws, 'assistant_text')
            if 'Human help requested' not in reply.get('text', ''):
                print(f'FAIL: unexpected first assistant_text payload: {reply}')
                return 2

        with client.websocket_connect(live_path) as ws2:
            ws2.send_json({'type': 'heartbeat', 'session_id': session_id, 'timestamp': '2026-03-05T00:00:00Z'})
            reconnect = recv_until_type(ws2, 'heartbeat_ack')
            if reconnect.get('session_id') != session_id:
                print(f'FAIL: reconnect heartbeat mismatch: {reconnect}')
                return 3

            ws2.send_json(
                {
                    'type': 'user_command',
                    'session_id': session_id,
                    'timestamp': '2026-03-05T00:00:00Z',
                    'command': 'describe_detailed',
                }
            )
            reply2 = recv_until_type(ws2, 'assistant_text')
            if 'Context snapshot:' not in reply2.get('text', ''):
                print(f'FAIL: unexpected assistant_text after reconnect: {reply2}')
                return 4

    print('PASS: ASGI reconnect flow succeeded.')
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Reconnect smoke test using FastAPI TestClient websockets.')
    parser.add_argument('--session-id', default='', help='Session ID (autogenerated when empty)')
    parser.add_argument('--ws-token', default=os.getenv('WS_AUTH_TOKEN', ''), help='Optional websocket auth token')
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    raise SystemExit(run(args))


if __name__ == '__main__':
    main()
